### ISSUE TITLE
TreatLife SS02s

### ISSUE THREAD

**Issue by fishmanone33** [Galveston01/tuya-adapter#17]
I get this device to connect but does not turn on or off.
https://www.amazon.com/Treatlife-Required-Assistant-Single-Pole-Schedule/dp/B07WWYQJFR

I think it is just config.  Info from tuya app

Code | Type | Values
switch_1 | Boolean | {true,false}
countdown_1 | Integer | {"unit":"s","min":0,"max":86400,"scale":0,"step":1}

**Comment by fishmanone33** [comment]
I figured it out had wrong key.  This is awesome thanks appreciate your work.

**Comment by bewee** [comment]
Glad to hear this fixed the problem. a8e66e35a82e98e720a21474e09c39effb7ee106 added your device to the compatibility list
