### ISSUE TITLE
Attach tarball to v0.2.1 release

### ISSUE THREAD

**Issue by mrstegeman** [Galveston01/tuya-adapter#18]
I'm moving add-on packages back out of S3 and I figured out the tarball was missing from your release tag for some reason.

https://s3-us-west-2.amazonaws.com/mozilla-gateway-addons/tuya-adapter-0.2.1.tgz

**Comment by bewee** [comment]
Hi @mrstegeman,

oh, you're right. I have no idea how this happened🤔 
But you just made me see that this release is quite deprecated by now anyway, so I will just create a new one :)

Regards
