### ISSUE TITLE
Lumary Dimmer Switch Configuration 

### ISSUE THREAD

**Issue by LionMike** [Galveston01/tuya-adapter#7]
I added a Lumary Dimmer Switch L-DS100. When type is set as switch it only has on/off. When set as a thing it has no function available. Set type as a lamp and used configuration below. Seems to work best with non-LED dimmable bulbs such as incandescent or halogen bulbs. Could not remove lighttemp setting in config as they returned when using switch.

`{"dps":{"on":1,"brightness":2,"lighttemperature":3},"minbrightness":0,"maxbrightness":100,"minlighttemperature":0,"maxlighttemperature":1000}`

**Comment by bewee** [comment]
Could you please change device type to (empty) and then control the device using the Smart Life app? Does this lead to an update of the device view in the WebThings Gateway (maybe you have to reload the webpage)? If so, please send a screenshot of the new device view and describe how each property you see there works.

**Comment by LionMike** [comment]
It is not connected to Smart Life. When I used the tuya-cli tool to find the localkey it never connected to  the Smart life app. If I connect to Smart Life app now will it send a new key and make the switch unusable in Webthings?

**Comment by bewee** [comment]
Yes, thought you may have connected it any differently. But no problem, then we will try to work with what you found out when using it as lamp. Just to make sure: The dimmer can be turned on and off and its brightness can be set, that's it?
And concerning the brightness: Which value do you have to select in order to achieve minimum/maximum brightness?

**Comment by LionMike** [comment]
Apparently Tuya is now blocking any attempt to run the app I was using, (Ucomen) from running through a proxy server, (Burp) as I would receive network failure messages through the app when trying that method. I feel lucky to have been able to get local keys for all my devices with the cli tool as it took me a better part of a day to do so.(I got a lot of timeouts) 

The  dimmer can be turned on and off and brightness can be set. After trying different values for both, minimum brightness set to 0 maximum to 100 worked the best. When set below a certain threshold approximately 25% the LED bulbs I tested would flicker. i think this is more an issue with the bulbs rather than the switch.

**Comment by bewee** [comment]
c054e734778454c054d0b07573ae623284cc73ec added support for dimmer device type. Please use config `{"maxlevel":100}` and report back whether this works.
It may be that the dimmer preview icon does not get updated according to the value of level property. This is due to a bug in the WebThings Gateway itself and will be fixed in its next update.

**Comment by LionMike** [comment]
It works!
 I also have a list of some some sockets and devices that I would like to add to your compatibility list. Should I post those as a new issue?

**Comment by bewee** [comment]
Either this, or you could just as well edit the `README.md` file on your own (click the pencil icon in the upper right corner in order to do so). If you save your changes, it will create a pull request which I can then merge into the repository.

**Comment by bewee** [comment]
> It works!
> I also have a list of some some sockets and devices that I would like to add to your compatibility list. Should I post those as a new issue?

Is this still the case?

**Comment by LionMike** [comment]
Yes. I forgot. Been working with Zigbee and Zwave devices.

**Comment by LionMike** [comment]
Here is the list I promised you.

Plugs:
Oukitel P1 dual smart plug. 
CooWoo AW01 smart plug. 
Tessan wall switch (same as Martin Jerry). 
Pinlo Smart strip (4 plugs and 4 USB).  
XS-SSA01 mini smart socket (unbranded). 
W-US002 smart socket (unbranded). 
Yuntong Smart relay (similar to Sonoff).

Bulbs:
Godotek 
Luntak
Nephalae
Manzoku

Miscellaneous:
Uenjoy Embedded 28.5" Electric Fireplace Insert Heater Log Flame with Remote Control. (Five light brightness settings plus completely off. Two heat settings plus no heat).

**Comment by bewee** [comment]
And these work properly out of the box? Or did you have to manually alter the configuration (in this case it would be great if you could send the configuration as well)?
Anyway, this fireplace is awesome😁 Which device type is this even?

**Comment by LionMike** [comment]
The bulbs all worked properly out of the box. I did try changing some settings manually on a couple of multiple sockets, as they show as off when socket one is off and two is on, but I couldn't get the configuration settings to work.  The heater showed up as a custom thing with type not specified and configuration: {"dps":{}}
Overall things are working quite well!

![Screenshot_2020-06-06 WebThings Gateway](https://user-images.githubusercontent.com/47491873/83958979-8f5e1300-a83d-11ea-8144-010a3ebc8f38.png)

**Comment by bewee** [comment]
I'm happy to hear this!
Concerning the issue with plugs with multiple sockets: That's unfortunately a problem of the Gateway itself.
Concerning the heater: I guess dps 1 is on/off, 102 is brightness (0 up to 5) and 101 is heat (0 up to 2)? If you can tell me whether this is correct (and if it is not how else it works), I can add a real internal device type for this.

**Comment by LionMike** [comment]
Thanks for the info on plugs and sockets. You are correct with the heater configuration.  because the icon just showed as Thing, I found a fireplace icon to use.

**Comment by bewee** [comment]
Added device type fireplace heater: 50eae8c2775aa8ee3b9ec8b43185713445f52da8
Could you test it using the following configuration?
`{"minlevel":0,"maxlevel":2,"minbrightness":0,"maxbrightness":5}`

**Comment by bewee** [comment]
Also, could you please check whether the links in this list are correctly (and, if possible, complete the missing ones)?

----------

## Plugs
- <a href='https://www.amazon.com/dp/B079KYVRN8/'>Oukitel P1 dual smart plug</a>
- CooWoo AW01 smart plug
- <a href='https://www.amazon.com/dp/B076VRH9WP'>Pinlo Smart strip</a>
- <a href='https://www.amazon.com/dp/B083Z4HPJX'>XS-SSA01 mini smart socket</a>
- <a href='https://www.amazon.com/dp/B07Q2P77JL'>W-US002 smart socket</a>
- Yuntong Smart relay

## Switches
- <a href='https://www.amazon.com.au/dp/B07GSTJ8TV'>Martin Jerry / Tessan wall switch</a>

## Colour Light bulbs
- <a href='https://www.amazon.com/dp/B07WGL5L8Q'>Godotek</a>
- <a href='https://www.amazon.com/dp/B07TNS9Y36'>Luntak</a>
- Nephalae
- <a href='https://www.amazon.com/dp/B073PZMBHF'>Manzoku</a>

## Fireplace Heaters
- <a href='https://stoves.stovesguide.biz/uenjoy-embedded-electric-fireplace-insert-heater.html'>Uenjoy Embedded 28.5" Electric Fireplace Insert Heater Log Flame</a>

**Comment by LionMike** [comment]
Changed dps  settings . Works fine. 
Fixing links:

Oukitel P1 dual smart plug 
https://www.amazon.com/Outlets-OUKITEL-Smart-control-required-Grey/dp/B07MNH3BMS

CooWoo AW01 smart plug
https://www.amazon.com/Compatible-Required-Enabled-Control-Function/dp/B079GT5JFS

W-US002 smart socket 
https://www.amazon.com/dp/B077S69421?tag=duckduckgo-ffcm-20&linkCode=osi&th=1&psc=1

Yuntong Smart relay
https://www.amazon.de/gp/product/B079L6GVNF/?tag=tasmotatempla-21

Godotek 
https://www.amazon.com/gp/product/B07R9LKWWJ/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Nephalae
https://www.amazon.com/gp/product/B07H36GG8L/ref=ppx_yo_dt_b_asin_title_o07_s00?ie=UTF8&psc=1

Luntak
https://www.amazon.com/gp/product/B07PFS7RY5/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

Manzoku
https://www.amazon.com/gp/product/B07HHYK14L/ref=as_li_ss_tl?ie=UTF8&psc=1&linkCode=sl1&tag=isitworthit12-20&linkId=9ad78fb1b25ecdd0fbcda18b63001b1f&language=en_US

**Comment by bewee** [comment]
Thank you very much
